### ISSUE TITLE
Remove permission node mock.on

### ISSUE THREAD

**Issue by ItzBlue72** [Heisenburger69/aDvaNceDmOcK#1]
Having that permission node means that all of my operators (myself included) will join with mock turned on automatically. The simple solution would just be to have them do `/mocking off` every time they join, but that's rather annoying. I think it would be better to make a command that enables that or remove the permission node entirely.

**Comment by varunbln** [comment]
As you can see here:
https://github.com/Heisenburger69/aDvaNceDmOcK/blob/master/plugin.yml#L83
The permission is not given to operators by default. You are most likely giving it yourself using an external permissions plugin like PurePerms
